catch blame(blame("this should explode")) {
    log "we shouldn't have reached this block"
}
